// Auto-generated from: test_invalid_encodings.btasm
// Generated: 2025-12-19 04:31:02
// Instruction count: 29

initial begin
    imem[0] = '{ T_POS_ONE, T_POS_ONE, T_ZERO, T_ZERO, T_ZERO, T_ZERO, T_ZERO, T_NEG_ONE, T_ZERO };
    imem[1] = '{ T_ZERO, T_ZERO, T_ZERO, T_ZERO, T_POS_ONE, T_ZERO, T_ZERO, T_ZERO, T_ZERO };
    imem[2] = '{ T_ZERO, T_POS_ONE, T_ZERO, T_ZERO, T_NEG_ONE, T_ZERO, T_ZERO, T_NEG_ONE, T_ZERO };
    imem[3] = '{ T_NEG_ONE, T_ZERO, T_NEG_ONE, T_ZERO, T_NEG_ONE, T_ZERO, T_ZERO, T_ZERO, T_ZERO };
    imem[4] = '{ T_NEG_ONE, T_ZERO, T_NEG_ONE, T_ZERO, T_NEG_ONE, T_ZERO, T_POS_ONE, T_ZERO, T_ZERO };
    imem[5] = '{ T_POS_ONE, T_POS_ONE, T_ZERO, T_ZERO, T_ZERO, T_POS_ONE, T_ZERO, T_NEG_ONE, T_ZERO };
    imem[6] = '{ T_NEG_ONE, T_NEG_ONE, T_ZERO, T_ZERO, T_POS_ONE, T_POS_ONE, T_ZERO, T_NEG_ONE, T_ZERO };
    imem[7] = '{ T_POS_ONE, T_POS_ONE, T_ZERO, T_POS_ONE, T_NEG_ONE, T_POS_ONE, T_ZERO, T_ZERO, T_ZERO };
    imem[8] = '{ T_ZERO, T_ZERO, T_ZERO, T_ZERO, T_ZERO, T_ZERO, T_ZERO, T_NEG_ONE, T_NEG_ONE };
    imem[9] = '{ T_ZERO, T_ZERO, T_ZERO, T_ZERO, T_ZERO, T_ZERO, T_ZERO, T_NEG_ONE, T_NEG_ONE };
    imem[10] = '{ T_ZERO, T_ZERO, T_ZERO, T_ZERO, T_ZERO, T_ZERO, T_ZERO, T_NEG_ONE, T_NEG_ONE };
    imem[11] = '{ T_ZERO, T_ZERO, T_ZERO, T_ZERO, T_ZERO, T_ZERO, T_ZERO, T_NEG_ONE, T_NEG_ONE };
    imem[12] = '{ T_ZERO, T_POS_ONE, T_ZERO, T_ZERO, T_ZERO, T_NEG_ONE, T_ZERO, T_NEG_ONE, T_ZERO };
    imem[13] = '{ T_ZERO, T_ZERO, T_ZERO, T_ZERO, T_ZERO, T_POS_ONE, T_ZERO, T_NEG_ONE, T_ZERO };
    imem[14] = '{ T_ZERO, T_ZERO, T_ZERO, T_ZERO, T_POS_ONE, T_NEG_ONE, T_ZERO, T_NEG_ONE, T_ZERO };
    imem[15] = '{ T_ZERO, T_ZERO, T_ZERO, T_ZERO, T_ZERO, T_POS_ONE, T_POS_ONE, T_NEG_ONE, T_ZERO };
    imem[16] = '{ T_ZERO, T_POS_ONE, T_ZERO, T_ZERO, T_POS_ONE, T_NEG_ONE, T_ZERO, T_NEG_ONE, T_ZERO };
    imem[17] = '{ T_POS_ONE, T_NEG_ONE, T_ZERO, T_ZERO, T_POS_ONE, T_ZERO, T_ZERO, T_NEG_ONE, T_ZERO };
    imem[18] = '{ T_ZERO, T_ZERO, T_POS_ONE, T_ZERO, T_NEG_ONE, T_ZERO, T_ZERO, T_ZERO, T_NEG_ONE };
    imem[19] = '{ T_POS_ONE, T_ZERO, T_ZERO, T_ZERO, T_ZERO, T_ZERO, T_ZERO, T_NEG_ONE, T_POS_ONE };
    imem[20] = '{ T_ZERO, T_ZERO, T_ZERO, T_ZERO, T_POS_ONE, T_NEG_ONE, T_ZERO, T_NEG_ONE, T_ZERO };
    imem[21] = '{ T_POS_ONE, T_POS_ONE, T_ZERO, T_ZERO, T_ZERO, T_POS_ONE, T_POS_ONE, T_POS_ONE, T_NEG_ONE };
    imem[22] = '{ T_ZERO, T_POS_ONE, T_ZERO, T_POS_ONE, T_ZERO, T_POS_ONE, T_ZERO, T_ZERO, T_ZERO };
    imem[23] = '{ T_ZERO, T_POS_ONE, T_ZERO, T_POS_ONE, T_ZERO, T_POS_ONE, T_ZERO, T_ZERO, T_ZERO };
    imem[24] = '{ T_ZERO, T_ZERO, T_ZERO, T_ZERO, T_POS_ONE, T_ZERO, T_ZERO, T_NEG_ONE, T_ZERO };
    imem[25] = '{ T_ZERO, T_ZERO, T_POS_ONE, T_ZERO, T_ZERO, T_NEG_ONE, T_POS_ONE, T_ZERO, T_NEG_ONE };
    imem[26] = '{ T_ZERO, T_ZERO, T_POS_ONE, T_ZERO, T_POS_ONE, T_NEG_ONE, T_ZERO, T_ZERO, T_NEG_ONE };
    imem[27] = '{ T_ZERO, T_ZERO, T_ZERO, T_ZERO, T_ZERO, T_ZERO, T_ZERO, T_NEG_ONE, T_NEG_ONE };
    imem[28] = '{ T_ZERO, T_ZERO, T_ZERO, T_ZERO, T_ZERO, T_ZERO, T_POS_ONE, T_NEG_ONE, T_NEG_ONE };
end
