// Auto-generated from: test_control_flow.btasm
// Generated: 2025-12-19 04:31:02
// Instruction count: 42

initial begin
    imem[0] = '{ T_NEG_ONE, T_NEG_ONE, T_ZERO, T_ZERO, T_POS_ONE, T_ZERO, T_ZERO, T_NEG_ONE, T_ZERO };
    imem[1] = '{ T_NEG_ONE, T_NEG_ONE, T_ZERO, T_ZERO, T_NEG_ONE, T_ZERO, T_ZERO, T_NEG_ONE, T_ZERO };
    imem[2] = '{ T_NEG_ONE, T_ZERO, T_POS_ONE, T_ZERO, T_ZERO, T_POS_ONE, T_ZERO, T_NEG_ONE, T_ZERO };
    imem[3] = '{ T_ZERO, T_NEG_ONE, T_ZERO, T_ZERO, T_ZERO, T_POS_ONE, T_ZERO, T_NEG_ONE, T_ZERO };
    imem[4] = '{ T_ZERO, T_POS_ONE, T_ZERO, T_ZERO, T_ZERO, T_POS_ONE, T_ZERO, T_NEG_ONE, T_ZERO };
    imem[5] = '{ T_NEG_ONE, T_NEG_ONE, T_ZERO, T_ZERO, T_POS_ONE, T_ZERO, T_ZERO, T_NEG_ONE, T_ZERO };
    imem[6] = '{ T_NEG_ONE, T_POS_ONE, T_ZERO, T_ZERO, T_NEG_ONE, T_ZERO, T_ZERO, T_NEG_ONE, T_ZERO };
    imem[7] = '{ T_NEG_ONE, T_ZERO, T_POS_ONE, T_ZERO, T_ZERO, T_POS_ONE, T_ZERO, T_NEG_ONE, T_ZERO };
    imem[8] = '{ T_ZERO, T_POS_ONE, T_ZERO, T_ZERO, T_POS_ONE, T_POS_ONE, T_ZERO, T_NEG_ONE, T_ZERO };
    imem[9] = '{ T_POS_ONE, T_NEG_ONE, T_ZERO, T_ZERO, T_NEG_ONE, T_POS_ONE, T_ZERO, T_NEG_ONE, T_ZERO };
    imem[10] = '{ T_POS_ONE, T_ZERO, T_ZERO, T_ZERO, T_POS_ONE, T_ZERO, T_ZERO, T_NEG_ONE, T_ZERO };
    imem[11] = '{ T_ZERO, T_NEG_ONE, T_ZERO, T_ZERO, T_NEG_ONE, T_ZERO, T_ZERO, T_NEG_ONE, T_ZERO };
    imem[12] = '{ T_NEG_ONE, T_ZERO, T_POS_ONE, T_ZERO, T_ZERO, T_POS_ONE, T_POS_ONE, T_NEG_ONE, T_ZERO };
    imem[13] = '{ T_ZERO, T_NEG_ONE, T_ZERO, T_ZERO, T_ZERO, T_NEG_ONE, T_ZERO, T_NEG_ONE, T_ZERO };
    imem[14] = '{ T_ZERO, T_POS_ONE, T_ZERO, T_ZERO, T_ZERO, T_NEG_ONE, T_ZERO, T_NEG_ONE, T_ZERO };
    imem[15] = '{ T_POS_ONE, T_POS_ONE, T_ZERO, T_ZERO, T_POS_ONE, T_ZERO, T_ZERO, T_NEG_ONE, T_ZERO };
    imem[16] = '{ T_POS_ONE, T_POS_ONE, T_ZERO, T_ZERO, T_NEG_ONE, T_ZERO, T_ZERO, T_NEG_ONE, T_ZERO };
    imem[17] = '{ T_NEG_ONE, T_ZERO, T_POS_ONE, T_ZERO, T_ZERO, T_POS_ONE, T_POS_ONE, T_NEG_ONE, T_ZERO };
    imem[18] = '{ T_ZERO, T_POS_ONE, T_ZERO, T_ZERO, T_POS_ONE, T_NEG_ONE, T_ZERO, T_NEG_ONE, T_ZERO };
    imem[19] = '{ T_POS_ONE, T_NEG_ONE, T_ZERO, T_ZERO, T_NEG_ONE, T_NEG_ONE, T_ZERO, T_NEG_ONE, T_ZERO };
    imem[20] = '{ T_ZERO, T_ZERO, T_ZERO, T_ZERO, T_POS_ONE, T_ZERO, T_ZERO, T_NEG_ONE, T_ZERO };
    imem[21] = '{ T_ZERO, T_ZERO, T_POS_ONE, T_ZERO, T_ZERO, T_POS_ONE, T_ZERO, T_NEG_ONE, T_ZERO };
    imem[22] = '{ T_ZERO, T_NEG_ONE, T_ZERO, T_ZERO, T_ZERO, T_POS_ONE, T_ZERO, T_NEG_ONE, T_ZERO };
    imem[23] = '{ T_POS_ONE, T_ZERO, T_ZERO, T_ZERO, T_ZERO, T_POS_ONE, T_ZERO, T_NEG_ONE, T_ZERO };
    imem[24] = '{ T_ZERO, T_POS_ONE, T_ZERO, T_ZERO, T_POS_ONE, T_ZERO, T_ZERO, T_NEG_ONE, T_ZERO };
    imem[25] = '{ T_ZERO, T_ZERO, T_POS_ONE, T_ZERO, T_ZERO, T_POS_ONE, T_ZERO, T_NEG_ONE, T_ZERO };
    imem[26] = '{ T_POS_ONE, T_ZERO, T_ZERO, T_ZERO, T_POS_ONE, T_POS_ONE, T_ZERO, T_NEG_ONE, T_ZERO };
    imem[27] = '{ T_POS_ONE, T_POS_ONE, T_ZERO, T_ZERO, T_NEG_ONE, T_POS_ONE, T_ZERO, T_NEG_ONE, T_ZERO };
    imem[28] = '{ T_NEG_ONE, T_POS_ONE, T_ZERO, T_ZERO, T_POS_ONE, T_ZERO, T_ZERO, T_NEG_ONE, T_ZERO };
    imem[29] = '{ T_ZERO, T_ZERO, T_POS_ONE, T_ZERO, T_ZERO, T_POS_ONE, T_POS_ONE, T_NEG_ONE, T_ZERO };
    imem[30] = '{ T_ZERO, T_NEG_ONE, T_ZERO, T_ZERO, T_ZERO, T_NEG_ONE, T_ZERO, T_NEG_ONE, T_ZERO };
    imem[31] = '{ T_POS_ONE, T_ZERO, T_ZERO, T_ZERO, T_ZERO, T_NEG_ONE, T_ZERO, T_NEG_ONE, T_ZERO };
    imem[32] = '{ T_ZERO, T_ZERO, T_ZERO, T_ZERO, T_POS_ONE, T_ZERO, T_ZERO, T_NEG_ONE, T_ZERO };
    imem[33] = '{ T_ZERO, T_ZERO, T_POS_ONE, T_ZERO, T_ZERO, T_POS_ONE, T_POS_ONE, T_NEG_ONE, T_ZERO };
    imem[34] = '{ T_POS_ONE, T_ZERO, T_ZERO, T_ZERO, T_POS_ONE, T_NEG_ONE, T_ZERO, T_NEG_ONE, T_ZERO };
    imem[35] = '{ T_POS_ONE, T_POS_ONE, T_ZERO, T_ZERO, T_NEG_ONE, T_NEG_ONE, T_ZERO, T_NEG_ONE, T_ZERO };
    imem[36] = '{ T_ZERO, T_POS_ONE, T_ZERO, T_ZERO, T_POS_ONE, T_ZERO, T_ZERO, T_NEG_ONE, T_ZERO };
    imem[37] = '{ T_POS_ONE, T_ZERO, T_ZERO, T_POS_ONE, T_ZERO, T_ZERO, T_POS_ONE, T_ZERO, T_ZERO };
    imem[38] = '{ T_POS_ONE, T_ZERO, T_POS_ONE, T_POS_ONE, T_ZERO, T_ZERO, T_POS_ONE, T_ZERO, T_ZERO };
    imem[39] = '{ T_POS_ONE, T_ZERO, T_ZERO, T_NEG_ONE, T_ZERO, T_ZERO, T_POS_ONE, T_ZERO, T_ZERO };
    imem[40] = '{ T_POS_ONE, T_ZERO, T_POS_ONE, T_NEG_ONE, T_ZERO, T_ZERO, T_POS_ONE, T_ZERO, T_ZERO };
    imem[41] = '{ T_ZERO, T_ZERO, T_ZERO, T_ZERO, T_ZERO, T_ZERO, T_POS_ONE, T_NEG_ONE, T_NEG_ONE };
end
