name: Docker Build
description: Build an OpenLane Docker Container
inputs:
  arch:
    description: "The Docker architecture/platform to build for"
    required: true
    default: "amd64"
  container_registry:
    description: Container registry
    required: true
    default: "ghcr.io"
  container_registry_user:
    description: Container registry user
    required: false
    default: ""
  container_registry_password:
    description: Container registry password or token
    required: false
    default: ""
  tool_repository:
    description: The Docker repository in which to store tools
    required: false
    default: "ghcr.io/the-openroad-project/openlane-tools"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-buildx-action@v2
    - uses: ./.github/actions/set_env_variables

    - name: Check If Going To Push An Image To Docker
      shell: bash
      run: |
        export PUSHING=$(ruby -e 'if ("${{ github.event_name }}" != "pull_request" && "${{ inputs.container_registry_user }}" != ""); print(1) else print(0) end')
        echo "PUSHING=$PUSHING" >> $GITHUB_ENV

    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.container_registry }}
        username: ${{ inputs.container_registry_user }}
        password: ${{ inputs.container_registry_password }}

    - name: Docker Build
      shell: bash
      run: |
        export BUILD_IF_CANT_PULL=1
        export BUILD_COMMAND="docker build"
        if [ "$PUSHING" = "1" ]; then
          export BUILD_IF_CANT_PULL_THEN_PUSH=1
          export BUILD_COMMAND="docker buildx build --load --cache-from=type=gha --cache-to=type=gha,scope=${{ github.workflow }}}"
        fi
        export BUILD_ARCH=${{ inputs.arch }}
        cd docker/ && make merge

    - name: Export Docker Image
      shell: bash
      run: docker save -o /tmp/image-${{ inputs.arch }}.tar ${{ env.OPENLANE_IMAGE_NAME }}-${{ inputs.arch }}

    - name: Upload Docker Image
      uses: actions/upload-artifact@v4
      with:
        name: docker-image-${{ inputs.arch }}
        path: /tmp/image-${{ inputs.arch }}.tar
