// Synthesized ternary netlist
// Generated by ternary_synth.py
// Total transistors: 336
//
// Cell Usage Summary:
// ----------------------------------------
//   BTFA    :    8 cells =   336 transistors
// ----------------------------------------
//   TOTAL: 8 cells = 336 transistors

module ternary_adder_8 (
  input  [1:0] a0,
  input  [1:0] a1,
  input  [1:0] a2,
  input  [1:0] a3,
  input  [1:0] a4,
  input  [1:0] a5,
  input  [1:0] a6,
  input  [1:0] a7,
  input  [1:0] b0,
  input  [1:0] b1,
  input  [1:0] b2,
  input  [1:0] b3,
  input  [1:0] b4,
  input  [1:0] b5,
  input  [1:0] b6,
  input  [1:0] b7,
  input  [1:0] cin,
  output [1:0] s0,
  output [1:0] s1,
  output [1:0] s2,
  output [1:0] s3,
  output [1:0] s4,
  output [1:0] s5,
  output [1:0] s6,
  output [1:0] s7,
  output [1:0] cout
);

  // Internal wires
  wire [1:0] n1;
  wire [1:0] n2;
  wire [1:0] n3;
  wire [1:0] n4;
  wire [1:0] n5;
  wire [1:0] n6;
  wire [1:0] n7;
  wire [1:0] n8;
  wire [1:0] n9;
  wire [1:0] n10;
  wire [1:0] n11;
  wire [1:0] n12;
  wire [1:0] n13;
  wire [1:0] n14;
  wire [1:0] n15;
  wire [1:0] n16;

  // Cell instances
  BTFA U_0 (.A(a0), .B(b0), .CIN(cin), .SUM(n1), .COUT(n2));
  BTFA U_1 (.A(a1), .B(b1), .CIN(n2), .SUM(n3), .COUT(n4));
  BTFA U_2 (.A(a2), .B(b2), .CIN(n4), .SUM(n5), .COUT(n6));
  BTFA U_3 (.A(a3), .B(b3), .CIN(n6), .SUM(n7), .COUT(n8));
  BTFA U_4 (.A(a4), .B(b4), .CIN(n8), .SUM(n9), .COUT(n10));
  BTFA U_5 (.A(a5), .B(b5), .CIN(n10), .SUM(n11), .COUT(n12));
  BTFA U_6 (.A(a6), .B(b6), .CIN(n12), .SUM(n13), .COUT(n14));
  BTFA U_7 (.A(a7), .B(b7), .CIN(n14), .SUM(n15), .COUT(n16));

  // Output assignments
  assign s0 = n1;
  assign s1 = n3;
  assign s2 = n5;
  assign s3 = n7;
  assign s4 = n9;
  assign s5 = n11;
  assign s6 = n13;
  assign s7 = n15;
  assign cout = n16;

endmodule