// Synthesized ternary netlist
// Generated by ternary_synth.py
// Total transistors: 168
//
// Cell Usage Summary:
// ----------------------------------------
//   BTFA    :    4 cells =   168 transistors
// ----------------------------------------
//   TOTAL: 4 cells = 168 transistors

module ternary_adder_4 (
  input  [1:0] a0,
  input  [1:0] a1,
  input  [1:0] a2,
  input  [1:0] a3,
  input  [1:0] b0,
  input  [1:0] b1,
  input  [1:0] b2,
  input  [1:0] b3,
  input  [1:0] cin,
  output [1:0] s0,
  output [1:0] s1,
  output [1:0] s2,
  output [1:0] s3,
  output [1:0] cout
);

  // Internal wires
  wire [1:0] n1;
  wire [1:0] n2;
  wire [1:0] n3;
  wire [1:0] n4;
  wire [1:0] n5;
  wire [1:0] n6;
  wire [1:0] n7;
  wire [1:0] n8;

  // Cell instances
  BTFA U_0 (.A(a0), .B(b0), .CIN(cin), .SUM(n1), .COUT(n2));
  BTFA U_1 (.A(a1), .B(b1), .CIN(n2), .SUM(n3), .COUT(n4));
  BTFA U_2 (.A(a2), .B(b2), .CIN(n4), .SUM(n5), .COUT(n6));
  BTFA U_3 (.A(a3), .B(b3), .CIN(n6), .SUM(n7), .COUT(n8));

  // Output assignments
  assign s0 = n1;
  assign s1 = n3;
  assign s2 = n5;
  assign s3 = n7;
  assign cout = n8;

endmodule